
spring.cloud.discovery.enabled=false

server.port=8084
spring.application.name=ms-reservas

ms.propiedades.url=http://localhost:8081
ms.inquilinos.url=http://localhost:8083
ms.pagos.url=http://localhost:8085
ms.limpieza.url=http://localhost:8086
ms.mensajeria.url=http://localhost:8087
ms.precios.url=http://localhost:8088

spring.datasource.url=jdbc:mysql://localhost:3306/db_reservas
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console